[default]
# FMO_IDENTIFIER = "buy"
fmo_identifier = ["BUY", "SELL", "buy", "sell","Buy","Sell"]
# DIRECTION_1 = ["BUY", "buy", "Buy","long","LONG","Long"]


[testing]
# DIRECTION_1 = ["SELL", "sell", "Sell","short","SHORT","Short"]