name: â˜ï¸Deploy

on:
  workflow_run:
    workflows: [ğŸ³Docker]
    types:
        - completed
      
        # - name: Build and deploy the application to Koyeb
        #   uses: koyeb/action-git-deploy@v1
        #   with:
        #     service-env: "PORT=8000"
        #     service-ports: "8000:http"
        #     service-routes: "/:8000"